{% set name = "mypy-protobuf" %}
{% set version = "2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a6f43fd98237b3b422c997459546eb7d0437db6dcf61a911948d0435b3f67d6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - protoc-gen-mypy = mypy_protobuf:main

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - protobuf
    - six
    - setuptools

test:
  imports:
    - mypy_protobuf
  commands:
    - which protoc-gen-mypy

about:
  home: https://github.com/dropbox/mypy-protobuf
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Generate mypy stub files from protobuf specs

extra:
  recipe-maintainers:
    - hmaarrfk
