{% set name = "mypy-protobuf" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mypy-protobuf/mypy_protobuf-3.7.0.tar.gz
  sha256: 912fb281f7c7b3e3a7c9b8695712618a716fddbab70f6ad63eaf68eda80c5efe

build:
  number: 0
  entry_points:
    - protoc-gen-mypy = mypy_protobuf.main:main
    - protoc-gen-mypy_grpc = mypy_protobuf.main:grpc
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools >=42
    - wheel
  run:
    - python
    - protobuf >=4.25.3
    - types-protobuf >=4.24

test:
  requires:
    - pip
  imports:
    - mypy_protobuf
    - mypy_protobuf.extensions_pb2
  commands:
    - protoc-gen-mypy --version
    - protoc-gen-mypy_grpc --version
    - pip check

about:
  home: https://github.com/dropbox/mypy-protobuf
  dev_url: https://github.com/nipunn1313/mypy-protobuf
  doc_url: https://github.com/nipunn1313/mypy-protobuf
  summary: Generate mypy stub files from protobuf specs
  description: |
    Generate mypy stub files from protobuf specs
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - hmaarrfk
    - asford
